<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_GiftCard
 */
?>
<?php
if(Mage::helper('amgiftcard')->isEnableGiftFormInCart()):
?>
<script type="text/javascript">
    function amCheckGiftCard(){
        var giftCardCode = jQuery('#am_giftcard_code').val();
        jQuery.ajax({
            method: "POST",
            url: "<?php echo Mage::getUrl('amgiftcard/cart/ajax', array('_secure'=>true)) ?>",
            data: { code: giftCardCode },
            beforeSend: function(){
                jQuery('#span_message_please_wait').show();
            },
            success: function(result){
                jQuery('#span_message_please_wait').hide();
                jQuery("#amgiftcard_info").html(result);
            }
        });
    }

    function amSubmitForm(){
        jQuery('#amgiftcard-form').submit();
    }
</script>
<form id="amgiftcard-form" action="<?php echo $this->getUrl('amgiftcard/cart/add', array('_secure'=>true)) ?>" method="post">
	<div class="discount">
		<div id="amgiftcard_info">
            <div class="bolt-label"><?php echo $this->__('Enter giftcard card')?>:</div>
            <div>
                <button type="button" onclick="amCheckGiftCard();" title="<?php echo $this->__('Check Gift Card status') ?>" class="button cancel-coupon" value="<?php echo $this->__('Check Gift Card status') ?>"><span><span><?php echo $this->__('Check status') ?></span></span>
                </button>
            </div>
        </div>
		<span id="span_message_please_wait" class="please-wait" style="display:none;">
			<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
		</span>
		<h2><?php echo $this->__('Gift Cards') ?></h2>
		<div class="discount-form">
			<div class="input-box">
				<input class="input-text bolt-input" type="text" id="am_giftcard_code" name="am_giftcard_code" value="" />
			</div>
			<div class="buttons-set">
				<a type="button" title="<?php echo $this->__('Add Gift Card') ?>" class="button" onclick="amSubmitForm();" value="<?php echo $this->__('Add Gift Card') ?>"> <div class="bolt-arrow-right"></div></a>
			</div>

		</div>
	</div>
</form>
<?php /*

<div class="amgiftcard">
	<h2><?php echo $this->__('Gift Cards') ?></h2>
	<div id="amgiftcard_info"></div>
    <span id="span_message_please_wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
    </span>
	<form id="amgiftcard-form" action="<?php echo $this->getUrl('amgiftcard/cart/add') ?>" method="post">
		<fieldset>
			<label for="giftcard_code"><?php echo $this->__('Enter the gift card code') ?></label>
			<div class="v-fix"><input class="required-entry input-text" id="am_giftcard_code" name="am_giftcard_code" value="" /></div>
			<button class="button" onclick="amgiftcardForm.submit()" type="button" value="<?php echo $this->__('Add Gift Card') ?>"><span><span><?php echo $this->__('Add Gift Card') ?></span></span></button>
			<button class="button check-gc-status" onclick="amCheckGiftCard();" type="button" value="<?php echo $this->__('Check Gift Card status') ?>"><span><span><?php echo $this->__('Check Gift Card status') ?></span></span></button>
		</fieldset>
	</form>
</div>*/?>

<!--<script type="text/javascript">
	//<![CDATA[
	var amgiftcardForm = new VarienForm('amgiftcard-form');
	function amCheckGiftCard()
	{
		if (amgiftcardForm.validator && !amgiftcardForm.validator.validate()) {
			return false;
		}
		$('am_giftcard_code').value = $('am_giftcard_code').value.trim();
		new Ajax.Updater(
			'amgiftcard_info',
			'<?php //echo Mage::getUrl('amgiftcard/cart/ajax') ?>',
			{
				onCreate: function() {
					$('span_message_please_wait').show();
				},
				onComplete: function() {
					$('span_message_please_wait').hide();
				},
				parameters : {
					code : $('am_giftcard_code').value
				}
			}
		);
	}
	//]]>
</script>-->

<?php endif;?>