<?php
/**
 * Bolt magento plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2019 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var $this Bolt_Boltpay_Block_Catalog_Product_Boltpay */
?>
<?php if ($this->isEnabledProductPageCheckout()): ?>
    <?php if ($this->isSimpleProduct()):?>
    <div class="bolt-product-checkout-button"></div>
    <?php else:?>
    <div type="button" title="PPC" class="button btn-cart validation-passed" onclick="productPageCheckout.click(this)">
        <span>
            <span>Buy Now</span>
        </span>
    </div>
    <?php endif;?>
<?php endif; ?>
