<?php
/**
 * Bolt magento plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2019 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var $this Bolt_Boltpay_Block_Catalog_Product_Boltpay */
?>
<?php if ($this->isEnabledProductPageCheckout()): ?>
    <?php if (!$this->isSupportedProductType()):?>
    <script type="text/javascript">
        var stateOld = {};
        var stateNew = {};
        
        var startBolt = function() {
            Object.assign(stateOld, spConfig.state);
            if (JSON.stringify(stateOld) == JSON.stringify(stateNew)) {
                return;
            }
            Object.assign(stateNew, spConfig.state);
            jQuery('#ppcBuyNow').show();
            jQuery('div.bolt-product-checkout-button').html('');
        }
        if (typeof spConfig != 'undefined' && typeof spConfig.configureObservers != 'undefined') {
            spConfig.configureObservers.push(startBolt);
        }

        var productPageCheckout = new VarienForm('product_addtocart_form');
        productPageCheckout.form.observe('change', function(){
            jQuery('#ppcBuyNow').show();
            jQuery('div.bolt-product-checkout-button').html('');
        });

        productPageCheckout.click = function() {
            if (this.validator.validate()) {
                var data = this.form.serialize();
                data += '&isAjax=1';
                jQuery('#ajax_loader').show();
                try {
                    jQuery.ajax( {
                        url : "/boltpay/order/ppc",
                        dataType : 'json',
                        type : 'post',
                        data : data,
                        success : function(data) {
                            jQuery('#ajax_loader').hide();
                            jQuery('#ppcBuyNow').hide();
                            BoltCheckout.configureProductCheckout({"orderToken": data}, {}, {});
                        }
                    });
                } catch (e) {
                }
            }
        }.bind(productPageCheckout);
    </script>
    <?php endif;?>
<?php endif; ?>
