version: 2.1
orbs:
  slack: circleci/slack@3.3.0
  swissknife: roopakv/swissknife@0.26.0

commands:
  if-php-modified:
    description: Runs if any php file is modified
    parameters:
      steps:
        description: The steps to run if modified
        type: steps
    steps:
      - swissknife/run_if_modified:
          always-run-on-branch: master
          pattern: .*\.zip$
          steps-to-run: << parameters.steps >>
          use-divergence-point: true

  notify-buildcop:
    description: 'Notifies #mx-greenkeeper when a build on master fails.'
    steps:
      - slack/status:
          fail_only: true
          failure_message: ':red_circle: M1: A $CIRCLE_JOB job has failed!'
          only_for_branches: master
          webhook: $SLACK_GREENKEEPER_WEBHOOK

jobs:
  unit-php55-mage18:
    docker:
      - image: bylexus/apache-php55
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - if-php-modified
      - run:
          name: PHP 5.5 Magento 1.8
          command: |
            mkdir ./artifacts
            export TEST_ENV=php55-mage18
            PHPUNIT_PHAR=tests/unit/phpunit-4.8.36.phar MAGENTO_VERSION=magento-mirror-1.8.1.0 tests/scripts/ci.sh
      - store_artifacts:
          path: ./artifacts
      - notify-buildcop

  unit-php55-mage19:
    docker:
      - image: bylexus/apache-php55
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - if-php-modified
      - run:
          name: PHP 5.5 Magento 1.9
          command: |
            mkdir ./artifacts
            export TEST_ENV=php55-mage19
            PHPUNIT_PHAR=tests/unit/phpunit-4.8.36.phar MAGENTO_VERSION=magento-mirror-1.9.3.6 tests/scripts/ci.sh
      - store_artifacts:
          path: ./artifacts
      - notify-buildcop

  unit-php56-mage18:
    docker:
      - image: bylexus/apache-php56
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - if-php-modified
      - run:
          name: PHP 5.6 Magento 1.8
          command: |
            mkdir ./artifacts
            export TEST_ENV=php56-mage18
            PHPUNIT_PHAR=tests/unit/phpunit-5.7.9.phar MAGENTO_VERSION=magento-mirror-1.8.1.0 tests/scripts/ci.sh
      - store_artifacts:
          path: ./artifacts
      - notify-buildcop

  unit-php56-mage19:
    docker:
      - image: bylexus/apache-php56
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - if-php-modified
      - run:
          name: PHP 5.6 Magento 1.9
          command: |
            mkdir ./artifacts
            export TEST_ENV=php56-mage19
            PHPUNIT_PHAR=tests/unit/phpunit-5.7.9.phar MAGENTO_VERSION=magento-mirror-1.9.3.6 tests/scripts/ci.sh
      - store_artifacts:
          path: ./artifacts
      - notify-buildcop

  integration-sandbox:
    docker:
      - image: circleci/openjdk:latest-node
      - image: selenium/standalone-chrome
    steps:
      - checkout
      - run:
          name: Integration tests (only for circleci branch)
          command: |
            echo "Running integration tests"
            git clone git@github.com:BoltApp/integration-tests.git
            cd integration-tests
            npm install
            mkdir -p ./screenshots
            JUNIT_REPORT_DIR=./test-results SCREENSHOT_DIR=./screenshots TEST_ENV=sandbox npm run test-checkout-magento1
      - store_test_results:
          path: ./integration-tests/test-results
      - store_artifacts:
          path: ./integration-tests/screenshots
      - run:
          name: Generate Report
          command: |
            cd integration-tests
            npm run generate-report
          when: always
      - store_artifacts:
          path: ./integration-tests/allure-report
      - notify-buildcop

workflows:
  version: 2
  tests:
    jobs:
      - integration-sandbox:
          filters:
            branches:
              only:
                - circleci
      - unit-php55-mage18
      - unit-php55-mage19
      - unit-php56-mage18
      - unit-php56-mage19
