version: 2.1
orbs:
  slack: circleci/slack@3.3.0
  swissknife: roopakv/swissknife@0.25.0
commands:
  if-php-modified:
    description: Runs if any php file is modified
    parameters:
      steps:
        description: The steps to run if modified
        type: steps
    steps:
      - swissknife/run_if_modified:
          always-run-on-branch: master
          pattern: .*\.php$
          steps-to-run: << parameters.steps >>
          use-divergence-point: true
  notify-buildcop:
    description: 'Notifies #mx-greenkeeper when a build on master fails.'
    steps:
      - slack/status:
          fail_only: true
          failure_message: ':red_circle: M1: A $CIRCLE_JOB job has failed!'
          only_for_branches: master
          webhook: $SLACK_GREENKEEPER_WEBHOOK
jobs:
  unit-php56-mage19:
    docker:
      - image: bylexus/apache-php56
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - if-php-modified:
        steps:
          - run:
              name: PHP 5.6 Magento 1.9
              command: |
                mkdir ./artifacts
                export TEST_ENV=php56-mage19
                PHPUNIT_PHAR=tests/unit/phpunit-5.7.9.phar MAGENTO_VERSION=magento-mirror-1.9.3.6 tests/scripts/ci.sh
          - store_artifacts:
              path: ./artifacts
          - notify-buildcop
workflows:
  version: 2
  tests:
    jobs:
      - unit-php56-mage19