<?php
/**
 * Bolt magento plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2018 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$customerNote = $this->getCustomerNote();
if(!empty($customerNote)){
?>

<div class="col2-set order-info-box">
    <div class="box">
        <div class="box-title">
            <h2><?php echo $this->__('Customer Note'); ?></h2>
        </div>
        <div class="box-content">
            <?php
            echo nl2br(htmlentities(preg_replace('/\$/','\\\$', $customerNote), ENT_COMPAT, "UTF-8"));
            ?>
        </div>

    </div>
    <!--</div>-->
</div>
<div class="clear"></div>
<?php    
}
?>