<?php /* @var $this Mage_Core_Block_Template */?>
<?php $mage_version = Mage::getVersionInfo();?>
<?php if ($mage_version['major'] == 1 && $mage_version['minor'] ==8): ?>
<script
  type="text/javascript"
  src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'boltpay/jquery/jquery-1.11.3.min.js'; ?>">
</script>
<script
  type="text/javascript"
  src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'boltpay/jquery/jquery-migrate-1.2.1.min.js'; ?>">
</script>
<script
  type="text/javascript"
  src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'boltpay/jquery/jquery-noconflict.js'; ?>">
</script>
<?php endif; ?>