<?php
/**
 * Bolt magento plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2019 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /* @var $this Bolt_Boltpay_Block_Checkout_Boltpay */ ?>
<?php
$isAllowedConnectJs = $this->isAllowedConnectJsOnCurrentPage();
?>
<?php if ($isAllowedConnectJs): ?>
    <?php $publishableKey = $this->getPublishableKeyForRoute(); ?>
    <?php if ($publishableKey): ?>
        <script>
            var prototypeSub = String.prototype.sub;
            /**
             * This Interval function prevents error due to BoltCheckout being undefined.
             * It is similar to the Interval functionality in boltpay/replace.phtml
             */
            var processIntervalCounter = 0;
            var processIntervalProd = setInterval(
                function() {
                    processIntervalCounter++;
                    if (typeof BoltCheckout !== "undefined") {
                        clearInterval(processIntervalProd);
                        /**
                         * Resolve conflict between String.sub methods added by PrototypeJS and Bolt Connect
                         * by merging their functionalities based on arguments provided
                         * If no arguments - call Bolt(ES15) sub, otherwise call Prototype sub
                         */
                        var boltSub = String.prototype.sub;
                        String.prototype.sub = function () {
                            return (arguments.length == 0 ? boltSub : prototypeSub).apply(this, arguments);
                        };
                    }

                    if (processIntervalCounter > 50) {
                        clearInterval(processIntervalProd);
                    }
                }, 50
            );
        </script>
    <script src="<?=$this->getJsUrl();?>" id="bolt-connect"
            type="text/javascript" data-shopping-cart-id="Magento"
            data-publishable-key="<?=$publishableKey?>"></script>
    <?php endif; ?>
<?php endif; ?>
