<?php
/**
 * Bolt magento plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2016-2020 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php   /* @var $this Bolt_Boltpay_Block_Checkout_Boltpay */ ?>
<div style="display:inline-block;">
    <div><?php echo Mage::helper('core')->quoteEscape($this->boltHelper()->__(Mage::getStoreConfig('payment/boltpay/title'))) ?></div>
    <img id="bolt-credit-card-logos" style="width:175px;" src="https://s3-us-west-1.amazonaws.com/bolt-public/magento-integration-release/powered_by_bolt_cards.png"
      alt="Mark" class="v-middle" />
</div>
<?php
$publishableKey = $this->boltHelper()->getPublishableKeyOnePage();
if (Mage::getStoreConfig('payment/boltpay/hide_on_checkout') || !$publishableKey) {
    ?>
<script>
    var bolt_payment_method = document.querySelectorAll('#p_method_boltpay');
    if (bolt_payment_method.length) {
        //hide the payment method
        bolt_payment_method[0].parentNode.style.display = 'none';
        bolt_payment_method[0].checked = false;
    }
</script>
<?php } ?>