<?php

$quote = Mage::getSingleton('checkout/session')->getQuote();

if($quote->getPayment()->getMethodInstance()->getCode() == 'boltpay'): ?>

    <?php $theme = Mage::getStoreConfig('payment/boltpay/theme'); ?>
    <div class="bolt-checkout-button with-cards <?= $theme; ?>"></div>
    <script type="text/javascript">

        (function() {

            var jsonpRequest = function(parent, element, attributes, params, callback_fn) {

                if (params) {

                    var ts  = new Date().getTime();
                    params.push('cachebust' + '=' + encodeURIComponent(ts));

                    if (callback_fn) params.push('callback' + '=' + encodeURIComponent(callback_fn));

                    params = params.join('&');
                    attributes.src += '?' + params;
                }

                var el = document.createElement(element);

                if (attributes) {
                    for (var attr in attributes) {
                        el.setAttribute(attr, attributes[attr]);
                    }
                }

                var parent = document.getElementsByTagName(parent)[0];
                parent.appendChild(el);
            };

            var loadConnectJS = function(key) {
                jsonpRequest('body', 'script', {"src": "<?= $this->getJsUrl(); ?>", "id":"bolt-connect", "type":"text/javascript", "data-shopping-cart-id":"Magento", "data-publishable-key":key});
            };

            loadConnectJS('<?=$this->getPaymentKey(false);?>');

            var retries = 50;

            var interval = setInterval(
                function() {

                    if (--retries <= 0) clearInterval(interval);

                    if (typeof BoltConnect !== "undefined") {
                        clearInterval(interval);
                        <?=$this->getCartDataJs(false); ?>
                    }
                }, 200);

        })();
    </script>
<?php else: ?>
    <?= $this->getChildHtml('button_original') ?>
<?php endif; ?>
