<?php /* @var $this Bolt_Boltpay_Block_Checkout_Popup */?>
<?php

?>

<div id="bolt-popup" class="bolt-popup">
    <div class="popup-wrapper">
        <div class="popup-title"></div>
        <div class="popup-content">
        </div>
        <div class="popup-action">
            <button class="popup-close btn-close">
                <?php echo $this->__('Close')?>
            </button>
        </div>
        <div class="popup-close">x</div>
    </div>
</div>

<script>
    var BoltPopup = {
        popupElmId: 'bolt-popup',
        popupElm: null,
        init: function() {
            this.popupElm = jQuery('#'+this.popupElmId);
            this.initPopupEvents()
        },
        initPopupEvents: function() {
            var self = this;

            if (!this.popupElm.length) {
                return false;
            }

            this.popupElm.find('.popup-close').on('click', function(event) {
                self.close();
            });
        },
        close: function() {
            this.popupElm.removeClass('active');
            this.popupElm.fadeOut();
        },
        show: function() {
            this.popupElm.addClass('active');

            this.popupElm.show();
        },
        addMessage: function(message) {
            if (message.length) {
                this.popupElm.find('.popup-content').html(message);
            }

            return this;
        }
    };
    BoltPopup.init();
</script>

<style>
    .bolt-popup {
        display: none;
        background: rgba(0,0,0,.8);
        height: 100vh;
        position: fixed;
        width: 100%;
        z-index: 99;
        left: 0;
        top: 0;
    }
    .popup-wrapper {
        position: absolute;
        max-width: 600px;
        width: 100%;
        left: 0;
        right: 0;
        margin: 0 auto;
        top: 50%;
        transform: translateY(-50%);
        background: #ffffff;
        border-radius: 10px;
        /*text-align: center;*/
        box-sizing: border-box;
        padding: 15px;
    }
    .popup-wrapper .popup-close {
        position: absolute;
        color: #fff;
        right: -10px;
        top: -30px;
        font-size: 20px;
    }
    .popup-wrapper .popup-close.btn-close {
        position: static;
    }
    .popup-wrapper .popup-title {
        font-size: 20px;
        text-align: center;
    }
    .popup-wrapper .popup-action {
        text-align: right;
    }
    .popup-wrapper .popup-action button {
        background: none;
        padding: 5px 10px;
        border: 1px solid #000000;
        -webkit-transform: all .5s;
        -moz-transform: all .5s;
        -ms-transform: all .5s;
        -o-transform: all .5s;
        transform: all .5s;
    }
    .popup-wrapper .popup-action button:hover {
        color: #ffffff;
        background: #000000;
    }
</style>
