<?php /* @var $this Mage_Core_Block_Template */?>

<div id="bolt-popup" class="bolt-popup" style="display: none;">
    <div class="popup-wrapper">
        <div class="popup-title"><?php echo $this->__('Bolt Checkout'); ?></div>
        <div class="popup-content"><?php echo $this->__('Sorry, but something went wrong. Please contact the seller.'); ?></div>
        <div class="popup-action">
            <button class="popup-close btn-close"><?php echo $this->__('Close')?></button>
        </div>
        <div class="popup-close icon-close">x</div>
    </div>
</div>

<script>
    var BoltPopup = {
        popupElmId: 'bolt-popup',
        popupElm: null,
        init: function() {
            this.popupElm = document.getElementById(this.popupElmId);
            this.initPopupEvents()
        },
        initPopupEvents: function() {
            var self = this;

            if (!this.popupElm) {
                return false;
            }

            var popup_close = this.popupElm.getElementsByClassName('popup-close')
            for (var i = 0; i < popup_close.length; i++) {
                popup_close[i].addEventListener( 'click', function() {
                    self.close();
                });
            }
        },
        close: function() {
            this.popupElm.classList.remove('active');
            this.fade();
        },
        show: function() {
            this.popupElm.classList.add('active');
            this.popupElm.style.display = "block";
        },
        fade: function () {
            element = this.popupElm;
            var op = 1;  // initial opacity
            var timer = setInterval(function () {
                if (op <= 0.1){
                    clearInterval(timer);
                    element.style.display = 'none';
                }
                element.style.opacity = op;
                element.style.filter = 'alpha(opacity=' + op * 100 + ")";
                op -= op * 0.1;
            }, 50);
        },
        addMessage: function(message) {
            this.popupElm.getElementsByClassName('popup-content')[0].innerHTML = message;
            return this;
        },
        setMessage: function(message) {
            this.addMessage(message);
        },
        setTitle: function(title) {
            this.popupElm.getElementsByClassName('.popup-title')[0].innerHTML = title;
            return this;
        }
    };
    BoltPopup.init();
</script>

<style>
    .bolt-popup {
        display: none;
        background: rgba(0,0,0,.8);
        height: 100vh;
        position: fixed;
        width: 100%;
        z-index: 99;
        left: 0;
        top: 0;
    }
    .bolt-popup .popup-wrapper {
        position: absolute;
        max-width: 600px;
        width: 100%;
        left: 0;
        right: 0;
        margin: 0 auto;
        top: 50%;
        transform: translateY(-50%);
        background: #ffffff;
        border-radius: 10px;
        /*text-align: center;*/
        box-sizing: border-box;
        padding: 15px;
    }
    .bolt-popup .popup-wrapper .popup-close {
        color: #fff;
        font-size: 20px;
        cursor: pointer;
    }
    .bolt-popup .popup-wrapper .popup-close.btn-close {
        position: static;
    }
    .bolt-popup .popup-wrapper .popup-close.icon-close {
        position: absolute;
        display: none;
        right: -10px;
        top: -30px;
    }
    .bolt-popup .popup-wrapper .popup-title {
        font-size: 20px;
        text-align: center;
    }
    .bolt-popup .popup-wrapper .popup-action {
        text-align: right;
    }
    .bolt-popup .popup-wrapper .popup-action button {
        background: none;
        padding: 6px 30px;
        border: 1px solid #268eff;
        color: #ffffff;
        background: #268eff;
        border-radius: 4px;
        margin: 15px 0;
        font-size: 16px;
    }
    .bolt-popup .popup-wrapper .popup-action button:hover {
        background: #0078fb;
        border-color: #0078fb;
    }
    .bolt-popup .popup-wrapper .popup-content {
        margin: 10px 0;
    }
</style>