<?php
/**
 * Bolt magento plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2018 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/* @var $this Bolt_Boltpay_Block_Checkout_Boltpay */

if($this->isBoltActive()) {
    ?>
    <script>
        (function () {
            var xmlhttp = new XMLHttpRequest();

            xmlhttp.open("POST", "<?php echo $this->helper()->getMagentoUrl('boltpay/shipping/prefetchEstimate');?>", true);
            xmlhttp.setRequestHeader("Content-type", "application/json");
            xmlhttp.onreadystatechange = function() {
                if (xmlhttp.readyState == XMLHttpRequest.DONE && xmlhttp.status == 200) {
                    var result = JSON.parse(xmlhttp.responseText);

                    if (result.address_data && Object.keys(result.address_data).length > 0) {
                        var evt = document.createEvent('HTMLEvents'),
                            _data = result.address_data,
                            postcode = document.getElementById('postcode'),
                            country = document.getElementById('country'),
                            region_id = document.getElementById('region_id'),
                            city = document.getElementById('city'),
                            region = document.getElementById('region');

                        if (postcode && !postcode.value.length && _data.postcode != null) {
                            postcode.value = _data.postcode;
                        }

                        if (country && !country.value.length && _data.country_id != null) {
                            evt.initEvent('change', true, true);
                            country.value = _data.country_id;
                            country.dispatchEvent(evt);
                        }
                        
                        if (city && !city.value.length && _data.city != null) {
                            city.value = _data.city;
                        }
                        
                        if (region_id && !region_id.value.length && _data.region_id != null) {
                            evt.initEvent('change', true, true);
                            region_id.value = _data.region_id;
                            region_id.dispatchEvent(evt);
                        }

                        if (region && !region.value.length && _data.region != null) {
                            if (region.tagName.toLowerCase() === 'input') {
                                region.value = _data.region;
                            } else if (region.tagName.toLowerCase() === 'select') {
                                evt.initEvent('change', true, true);
                                region.value = _data.region;
                                region.dispatchEvent(evt);
                            }
                        }
                    }
                }
            };
            xmlhttp.send(JSON.stringify(<?=$this->getLocationEstimate()?>));
        })();
    </script>
    <?php
}