<?php
/**
 * Bolt magento plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2018 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/********************************************************************
 * Bolt replace button JavaScript / CSS that's added to the firecheckout cart page
 ********************************************************************/
/** @var Bolt_Boltpay_Block_Checkout_Boltpay $this */
if(!Mage::helper('boltpay')->canUseBolt($this->getQuote(), false) || Mage::getStoreConfig('payment/boltpay/hide_on_checkout') ) return;

?>
<script>

    var isFireCheckoutFormValid = false;
    var initBoltButtons = function() {
        <?=$this->getCartDataJs(Bolt_Boltpay_Block_Checkout_Boltpay::CHECKOUT_TYPE_FIRECHECKOUT); ?>
    }

    var initializeBolt = function(){

        // checkout.setLoadWaiting(false);

        var place_order_buttons = document.querySelectorAll('<?=Mage::getStoreConfig('payment/boltpay/selectors');?>');

        place_order_buttons.forEach(
            function(place_order_button) {
                var bolt_button =  document.createElement("div");
                bolt_button.setAttribute("class", "bolt-checkout-button with-cards <?=$this->getCssSuffix(); ?> <?=$this->getTheme(); ?>");
                bolt_button.style.display = "none";

                place_order_button.parentNode.insertBefore(bolt_button, place_order_button);
            }
        );

        var bolt_buttons = document.querySelectorAll('.bolt-checkout-button');

        // Render Bolt button.
        initBoltButtons();

        /**
         * Click event to payment method radio buttons that toggle
         * display of the bolt button
         */
        var toggleBoltButton = function () {
            if (this.id == "p_method_boltpay") {
                bolt_buttons.forEach(
                    function (bolt_button) {
                        bolt_button.style.display="";
                    }
                );
                place_order_buttons.forEach(
                    function (place_order_button) {
                        place_order_button.style.display="none";
                    }
                );
            } else {
                bolt_buttons.forEach(
                    function (bolt_button) {
                        bolt_button.style.display="none";
                    }
                );
                place_order_buttons.forEach(
                    function (place_order_button) {
                        place_order_button.style.display="";
                    }
                );
            }
        };


        /**
         * Attaches click event to all radio buttons
         *
         * @param   An option list passed in by an observer if this function is called in that context
         *          This can be omitted.
         */
        var attachClickEvents = function(mutationList) {

            var payment_radios = document.querySelectorAll('[name="payment[method]"]');
            for (i = 0, length = payment_radios.length; i < length; i++) {

                var payment_radio = payment_radios[i];

                payment_radio.onclick = toggleBoltButton;

                <?php if ($this->isBoltOnlyPayment()): ?>
                if (payment_radio.id == "p_method_boltpay") {
                    payment_radio.click();
                } else {
                    payment_radio.parentNode.style.display = "none";
                }
                <?php endif; ?>

                if (payment_radio.checked) payment_radio.click();
            }

        }

        attachClickEvents();

        //////////////////////////////////////////////////////////////////////
        // Watch for changes in the payment methods to re-attach click events
        //////////////////////////////////////////////////////////////////////
        var paymentMethodsContainer = document.getElementById('checkout-payment-method-load');
        var paymentMethodObserver = new MutationObserver(attachClickEvents);
        paymentMethodObserver.observe(paymentMethodsContainer, { childList: true });
        //////////////////////////////////////////////////////////////////////

        var autoSelectShipping = function () {

            var shipping_selected = false;
            var shipping_methods  = document.querySelectorAll('input[name=shipping_method]');

            for (i = 0, length = shipping_methods.length; i < length; i++) {
                var shipping_method = shipping_methods[i];
                if (shipping_method.checked) {
                    shipping_selected = true;
                    shipping_method.click();
                }
            }

            if (!shipping_selected)  document.querySelectorAll('input[name=shipping_method]')[0].click();
        };

        if (window.addEventListener) {
            window.addEventListener("load", autoSelectShipping, false);
        } else if (window.attachEvent) {
            window.attachEvent("onload", autoSelectShipping);
        } else {
            window.onload = autoSelectShipping;
        }
    };

    if (window.addEventListener) {
        window.addEventListener("load", initializeBolt, false);
    } else if (window.attachEvent) {
        window.attachEvent("onload", initializeBolt);
    } else {
        window.onload = onloadCallback;
    }

</script>

<style>
    <?=$this->getSelectorsCSS();?>
    <?=$this->getAdditionalCSS();?>
</style>