<?php
/**
 * Bolt magento plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2016-2020 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /* @var $this Bolt_Boltpay_Block_Checkout_Boltpay */ ?>
<?php
$version = Bolt_Boltpay_Helper_ConfigTrait::getBoltPluginVersion();
?>
<?php if($this->isBoltActive()): ?>
    <script
            id="bolt-track"
            type="text/javascript"
            src="<?= $this->getTrackJsUrl(); ?>"
            data-publishable-key="<?=$this->getPublishableKeyForThisPage();?>">
    </script>
    <script>console.log("Bolt M1 Version: <?=$version?>");</script>
<?php endif; ?>

