<?php /** @var Bolt_Boltpay_Block_Adminhtml_System_Config_Form_Button $this */ ?>
<style>
    #row_payment_boltpay_checkapi .note span {
        color: red;
    }
</style>
<script>
    function check() {
        var apiKey = document.getElementById("payment_boltpay_api_key").value;
        var signingSecret = document.getElementById("payment_boltpay_signing_key").value;
        var keyOnepage = document.getElementById("payment_boltpay_publishable_key_onepage").value;
        var keyMultiPage = document.getElementById("payment_boltpay_publishable_key_multipage").value;
        var errorElement = document.querySelector('#row_payment_boltpay_checkapi .note span');
        var loadingElement = document.getElementById("loading-mask");
        var boltButtonElement = document.getElementById('boltpay_check_button');

        if (!apiKey) {
            errorElement.innerText = '<?php echo Mage::helper('boltpay')->__('API Key is required')?>';
            return;
        }
        if (!signingSecret) {
            errorElement.innerText = '<?php echo Mage::helper('boltpay')->__('Signing Secret is required')?>';
            return;
        }
        if (!keyOnepage && !keyMultiPage) {
            errorElement.innerText = '<?php echo Mage::helper('boltpay')->__('Field "Publishable Key - One Page Checkout" or "Publishable Key - Multi-Page Checkout" must contain a value.')?>';
            return;
        }

        loadingElement.style.display = "block";
        boltButtonElement.disabled = true;

        var xmlhttp = new XMLHttpRequest();

        xmlhttp.open("POST", "<?php echo Mage::helper('boltpay/api')->getMagentoUrl('boltpay/configuration/check');?>", true);
        xmlhttp.setRequestHeader("Content-type", "application/json");
        xmlhttp.onreadystatechange = function () {
            if (xmlhttp.readyState == XMLHttpRequest.DONE && xmlhttp.status == 200) {
                var result = JSON.parse(xmlhttp.responseText);

                if (!result.result) {
                    errorElement.innerText = result.message;
                } else {
                    errorElement.innerHTML = "<span style='color: green;'><?php echo Mage::helper('boltpay')->__('Valid configuration')?></span>";
                }
            }

            boltButtonElement.disabled = false;
            loadingElement.style.display = "none";
        };
        xmlhttp.send(JSON.stringify({store_id: <?php echo $this->getStoreId() ?>}));

    }
</script>

<?php echo $this->getButtonHtml() ?>