<?php
/**
 * Bolt magento plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2019 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var Bolt_Boltpay_Block_Adminhtml_System_Config_Form_Button $this */
?>
<style>
    #row_payment_keys_checkapi p.check_boltpay_api_error {
        color: red;
    }
</style>
<script>
    function check() {
        var apiKey = document.getElementById("payment_keys_api_key").value;
        var signingSecret = document.getElementById("payment_keys_signing_key").value;
        var keyOnePage = document.getElementById("payment_keys_publishable_key_onepage").value;
        var keyMultiPage = document.getElementById("payment_keys_publishable_key_multipage").value;
        var errorElement = document.querySelector('#row_payment_keys_checkapi p.check_boltpay_api_error');
        var loadingElement = document.getElementById("loading-mask");
        var boltButtonElement = document.getElementById('boltpay_check_button');

        if (!apiKey) {
            errorElement.innerText = '<?php echo $this->boltHelper()->__('API Key is required')?>';
            return;
        }
        if (!signingSecret) {
            errorElement.innerText = '<?php echo $this->boltHelper()->__('Signing Secret is required')?>';
            return;
        }
        if (!keyOnePage && !keyMultiPage) {
            errorElement.innerText = '<?php echo $this->boltHelper()->__('Field Publishable Key - Payment Only" or "Publishable Key - Multistep" must contain a value.')?>';
            return;
        }

        loadingElement.style.display = "block";
        boltButtonElement.disabled = true;

        var xmlhttp = new XMLHttpRequest();

        xmlhttp.open("POST", "<?php echo $this->boltHelper()->getMagentoUrl('boltpay/configuration/check');?>", true);
        xmlhttp.setRequestHeader("Content-type", "application/json");
        xmlhttp.onreadystatechange = function () {
            if (xmlhttp.readyState == XMLHttpRequest.DONE && xmlhttp.status == 200) {
                var result = JSON.parse(xmlhttp.responseText);

                if (!result.result) {
                    errorElement.innerText = result.message;
                } else {
                    errorElement.innerHTML = "<span style='color: green;'><?php echo $this->boltHelper()->__('Valid configuration')?></span>";
                }
            }

            boltButtonElement.disabled = false;
            loadingElement.style.display = "none";
        };
        xmlhttp.send(JSON.stringify({store_id: <?php echo $this->getStoreId() ?>}));

    }
</script>

<?php echo $this->getButtonHtml() ?>