<?php
/**
 * Bolt magento plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2018 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /* @var $this Bolt_Boltpay_Block_Checkout_Boltpay */ ?>
<?php
$isAllowedConnectJs = $this->isAllowedConnectJsOnCurrentPage();
?>
<?php if ($isAllowedConnectJs): ?>
    <?php
    $publishableKey = $this->getPublishableKeyForRoute();
    ?>
    <?php if ($publishableKey): ?>
        <script src="<?=$this->getJsUrl();?>" id="bolt-connect"
                type="text/javascript" data-shopping-cart-id="Magento"
                data-publishable-key="<?=$publishableKey?>">
        </script>
    <?php endif; ?>
<?php endif; ?>