<?php
/**
 * Bolt magento plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2019 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var Bolt_Boltpay_Block_Adminhtml_Notification $this */
$updateVersion = $this->getUpdater()->getLatestVersion();
$patchVersion = $this->getUpdater()->getPatchVersion(Bolt_Boltpay_Helper_ConfigTrait::getBoltPluginVersion());
$isPatch = $this->getUpdater()->getUpdateSeverity() == 'patch';
?>
<div class="notification-global" style="background: #fff9e9 url(<?php echo $this->getSeverityIconUrl() ?>) 27px 5px no-repeat; background-size: 15px 15px;">
    <strong>
        <?php echo $this->__(
            $isPatch ? 'Bolt version %s is available to address a CRITICAL issue.' : 'Bolt version %s is now available!',
            $isPatch ? $patchVersion : $updateVersion
        ); ?>
    </strong>
</div>
